os: linux
dist: xenial
language: python

python:
  - 3.7

cache:
  - pip

env:
  jobs:
    - SAM_RUNTIME=nodejs12.x
    - SAM_RUNTIME=python3.7

install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker info
  - pip3 install aws-sam-cli

script:
  - sam build --use-container --debug --template "sam--$SAM_RUNTIME.yml"

# This block will be executed even if the "script" fails.
# Here we show there is not issue with Travis and the
# image can be downloaded.
after_script:
  - docker pull "amazon/aws-sam-cli-build-image-$SAM_RUNTIME"
  - docker inspect "amazon/aws-sam-cli-build-image-$SAM_RUNTIME"
