os: linux
dist: xenial
language: python

python:
  - 3.7

cache:
  - pip

env:
  jobs:
    - SAM_RUNTIME=nodejs12.x DOCKER_PULL_BEFORE=no
    - SAM_RUNTIME=nodejs12.x DOCKER_PULL_BEFORE=yes
    - SAM_RUNTIME=python3.7 DOCKER_PULL_BEFORE=no
    - SAM_RUNTIME=python3.7 DOCKER_PULL_BEFORE=yes

install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker info
  - pip3 install aws-sam-cli

script:
  # Download the image manually and "sam build" will work.
  - if [ "$DOCKER_PULL_BEFORE" == "yes" ]; then
        docker pull "amazon/aws-sam-cli-build-image-$SAM_RUNTIME"
    fi
  - sam build --use-container --debug --template "sam--$SAM_RUNTIME.yml"
