os: linux
dist: xenial
language: python

python:
  - 3.7

cache:
  - pip

env:
  global:
    # AWS CLI reads this variable automatically.
    - AWS_DEFAULT_REGION=eu-west-1

install:
  - pip3 install awscli aws-sam-cli boto3

script:
  - sam build --use-container --debug
