AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Python:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
      Runtime: python3.7
      Policies: AmazonDynamoDBFullAccess
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/the/route'
            Method: get
